### ISSUE TITLE
ERD 설계

### ISSUE THREAD

**Issue by JongMinCh0i** [JongMinCh0i/capstone-project-withU#4]
ERD 설계도 프로토 타입 1차를 제출해주세요.

**Comment by Hamkua** [comment]
[](url)URL : https://aquerytool.com/aquerymain/index/?rurl=fd81860f-abb2-495e-ad3a-333a115c6675&
비밀번호 : 6d1tbv

AqueryTool에서 핵심 기능을 대략적으로 구상한 ERD 입니다.
![image](https://user-images.githubusercontent.com/84824124/223684482-fbe9a632-e1af-400b-b477-d6fb6e4d7327.png)

**Comment by JongMinCh0i** [comment]
감사합니다. 추후 변동 사항 있을 경우 잘 부탁드립니다!
