### ISSUE TITLE
캡스톤 프로젝트 화면 명세 작성

### ISSUE THREAD

**Issue by JongMinCh0i** [JongMinCh0i/capstone-project-withU#9]
@hwan035  @Ahnmandoo  FE 팀 프로젝트 화면 명세서 작성을 3/12 일 까지 부탁드립니다.

**Comment by JongMinCh0i** [comment]
https://ovenapp.io/view/tdYNqrTzH9IEnMmPZkGaGqXSsZIGps3N/YX9v6 
를 통해서 작성 완료 했음. (1차)

**Comment by JongMinCh0i** [comment]
https://ovenapp.io/view/PNvQen75jMyMgprnvgU6YWmFPFaTEBs4/ 
(2차)최종 완료 입니다.

**Comment by hwan035** [comment]
화면설계서(1차)입니다. 몇몇 사항은 회의를 통해 결정해야 할 것 같습니다.
[화면설계서1.pdf](https://github.com/JongMinCh0i/capstone-project-withU/files/10950440/1.pdf)
[화면설계서1.pptx](https://github.com/JongMinCh0i/capstone-project-withU/files/10950441/1.pptx)

**Comment by JongMinCh0i** [comment]
@hwan035 해당 화면 설계서를 바탕으로 BE 회의 진행 후 통합 회의를 진행 하겠습니다. 감사합니다.
